[package]
name = "abstract-algebra-first-course"
version = "0.1"
lean_version = "leanprover-community/lean:3.23.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "a64985169ea134c7c6057c4535c7bea4065b12f7"}
